version: '3'
services:

  guzman-mysql8:
    image: mysql:8
    container_name: guzman-mysql8
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=sasa
      - MYSQL_DATABASE=msvc_usuarios
    volumes:
      - /data-bbdd/mysql/:/var/lib/mysql

  guzman-postgres14:
    image: postgres:14-alpine
    container_name: guzman-postgres14
    ports:
      - 5532:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=msvc_cursos
      - POSTGRES_PASSWORD=sasa
    volumes:
      - /data-bbdd/postgresql/data:/var/lib/postgresql/data

  guzman-pgadmin:
    image: dpage/pgadmin4
    container_name: guzman-pgadmin
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=zinedine@rmad.com
      - PGADMIN_DEFAULT_PASSWORD=zinedine

  guzman-msvc-cursos:
    image: micro-cursos:latest
    container_name: guzman-msvc-cursos
    ports:
      - 15002:8002
    depends_on:
      - guzman-postgres14

  guzman-msvc-usuarios:
    image: micro-usuarios:latest
    container_name: guzman-msvc-usuarios
    ports:
      - 15001:8001
    depends_on:
      - guzman-mysql8

